### PR TITLE
Update FtpComponent.php

### PR DESCRIPTION
**Pull request by d4rkstar**
Hello, it seems that get and put have $mode in wrong place.
I've also fixed the event onFileDownlaoded in get method. It seems that for some reason the code contained an undefined variable. I think that $local_file is the right one.

### CODE REVIEW

**Comment by hguenot** [comment]
Hi,

Thanks for your help. 2 errors in your pull request : 
1. in method get, $mode must have a default value (because $local_file got one)
2. in method put, it will be better to have same format than get method... $mode should be the third parameter

Best regards
HG

**Comment by d4rkstar** [comment]
Sorry I was a bit busy. I see that you've already fixed all. You may also check whether you have upgraded Packagist? It seems to be behind at commit c05fcb0.

**Comment by hguenot** [comment]
Hi. Packagings bas bien updates. Y ou coule usé version V2.1.2.
Thanks for tour help.

**Comment by d4rkstar** [comment]
Great! Thank you!

**Pull request merged**
